import { ApplicationConfig, provideZoneChangeDetection } from "@angular/core";
import { provideRouter } from "@angular/router";
import { provideHttpClient, withXhr } from "@angular/common/http";
import { provideTranslateService } from "@ngx-translate/core";
import { provideTranslateHttpLoader } from "@ngx-translate/http-loader";
import {
  provideLucideIcons,
  LucideShieldCheck,
  LucideLayoutDashboard,
  LucideTruck,
  LucideFileText,
  LucideBell,
  LucideClipboardCheck,
  LucideLogOut,
  LucideMenu,
  LucideSearch,
  LucidePlus,
  LucideUpload,
  LucideDownload,
  LucideArrowLeft,
  LucideArrowRight,
  LucideRefreshCw,
  LucideCheck,
  LucideAlertTriangle,
  LucideClock,
  LucideEye,
  LucideSettings,
  LucideUser,
  LucideGlobe,
  LucideCheckCircle,
  LucideChevronRight,
  LucideHistory,
} from "@lucide/angular";
import { routes } from "./app.routes";
export const appConfig: ApplicationConfig = {
  providers: [
    provideZoneChangeDetection({ eventCoalescing: true }),
    provideHttpClient(withXhr()),
    provideRouter(routes),
    provideTranslateService({
      loader: provideTranslateHttpLoader({ prefix: "/i18n/", suffix: ".json" }),
      fallbackLang: "es",
      lang: "es",
    }),
    provideLucideIcons(
      LucideShieldCheck,
      LucideLayoutDashboard,
      LucideTruck,
      LucideFileText,
      LucideBell,
      LucideClipboardCheck,
      LucideLogOut,
      LucideMenu,
      LucideSearch,
      LucidePlus,
      LucideUpload,
      LucideDownload,
      LucideArrowLeft,
      LucideArrowRight,
      LucideRefreshCw,
      LucideCheck,
      LucideAlertTriangle,
      LucideClock,
      LucideEye,
      LucideSettings,
      LucideUser,
      LucideGlobe,
      LucideCheckCircle,
      LucideChevronRight,
      LucideHistory,
    ),
  ],
};
